### ISSUE TITLE
Sign function in ec_schnorr may not always succeed

### ISSUE THREAD

**Issue by AmritKumar** [GincoInc/zillean#11]
**PROBLEM:** Signing of messages should always succeed unless the internal libraries throw an error or an exception. The current implementation however may do a return as soon as either: 1) `k` is invalid 2) `r` is invalid 3) or `s` is invalid. This should not be the expected behavior of a signing function.

**SOLUTION:** There are two fixes that need to be implemented here. First, the random bytes `k` should be generated within `sign` function itself. It should not come from outside as being done currently using: ` k, _ := zillean.GenerateDRN(zillean.EncodeTransaction(rawTx))`. If the generated randomness does not satisfy the following conditions, then a new `k` should be generated in a while loop:
```
if _k.Cmp(big.NewInt(0)) == 0 || _k.Cmp(ecs.Curve.Params().N) >= 0 {
		return nil, nil, errors.New("Invalid k")
}
```  
Similarly, if for a given `k`, the generated `r` and `s` values are invalid, then instead of returning from the function, a new `k` must be generated. A straightforward fix would be to rename
 
```func (ecs *ECSchnorr) Sign(privKey, pubKey, k, msg []byte) ([]byte, []byte, error) { ... }```
 to 
```func (ecs *ECSchnorr) TrySign(privKey, pubKey, k, msg []byte) ([]byte, []byte, error) { ... }```
and then add another function `Sign` that makes a call to `TrySign` in a while loop. `Sign` could be the function that generates the random bytes `k` to be passed to `TrySign`.

**Comment by KazutakaNagata** [comment]
I appreciate your review. I will wok on it.

**Comment by KazutakaNagata** [comment]
@AmritKumar I changed Sign function so that it always returns signature as you advised. https://github.com/GincoInc/zillean/pull/13 Thank you very much for your support again!!
