### ISSUE TITLE
Incorrect GeneratePrivateKey()

### ISSUE THREAD

**Issue by AmritKumar** [GincoInc/zillean#9]
**PROBLEM:** The current implementation to generate private key is to fill a 32-byte array with random bytes. This is incorrect as the private key should be smaller than the curve order `n < 2^256`. And hence, the following code may end up generating an invalid private key. 

````
// GeneratePrivateKey generates a new private key for Schnorr signature.
func (ecs *ECSchnorr) GeneratePrivateKey() []byte {
	b := make([]byte, 32)
	rand.Read(b)
	return b
}
````

**SOLUTION:** The function should generate randomness in a while loop and then check whether the integer corresponding to the bytes generated is equal to 0 or larger than or equal to `n` (the group order). If any of these two cases is true, then, the function should regenerate new random byte arrays.

**Comment by KazutakaNagata** [comment]
Thank you very much for pointing it out. That's right. 
I should have checked the condition.

**Comment by KazutakaNagata** [comment]
@AmritKumar I've just fixed this issue. Could you kindly review it?https://github.com/GincoInc/zillean/pull/12

**Comment by AmritKumar** [comment]
@KazutakaNagata I can see some other issues in the implementation. But could not get time to issue tickets. Let me do that first and then I would love to review the PR.

**Comment by KazutakaNagata** [comment]
@AmritKumar Oh that will be very helpful!! Thank you so much again!
